/**
 * Style Dictionary configuration — Sugartown token pipeline
 *
 * Source: tokens/source/tokens.json (generated from tokens.css via migrate-css-to-json.mjs)
 * Outputs:
 *   - packages/design-system/src/styles/tokens.css  (DS package mirror)
 *   - apps/web/src/design-system/styles/tokens.css  (web canonical)
 *
 * Architecture notes:
 *   - Token names carry full st-* prefix in JSON; no platform prefix needed
 *   - outputReferences: true → var() references preserved (aliases, semantic tokens)
 *   - $type: "color" → css/color transform applies (lowercases hex — cosmetic difference from
 *     hand-authored file; CSS hex is case-insensitive so this is not a meaningful regression)
 *   - $type: "other" → passed through as literal string (color-mix, shadows, font stacks, etc.)
 *   - Selector: :root — dark-first defaults live in tokens.css; theme overrides in theme.pink-moon.css
 */

import StyleDictionary from 'style-dictionary';

const sharedFileConfig = {
  format: 'css/variables',
  options: {
    selector: ':root',
    outputReferences: true,
    // fileHeader callback returns lines that go inside the /* */ block (no wrapping needed)
    fileHeader: () => [
      'Sugartown Design System Tokens',
      'Do not edit directly — generated by Style Dictionary from tokens/source/tokens.json',
      'Regenerate: pnpm tokens:build',
    ],
  },
};

const sd = new StyleDictionary({
  source: ['tokens/source/tokens.json'],
  platforms: {
    'css-ds-package': {
      transformGroup: 'css',
      buildPath: 'packages/design-system/src/styles/',
      files: [{ ...sharedFileConfig, destination: 'tokens.css' }],
    },
    'css-web-app': {
      transformGroup: 'css',
      buildPath: 'apps/web/src/design-system/styles/',
      files: [{ ...sharedFileConfig, destination: 'tokens.css' }],
    },
  },
});

await sd.buildAllPlatforms();
console.log('\n✅ tokens:build complete');
